### ISSUE TITLE
[Feature] Tell when file listing is done

### ISSUE THREAD

**Issue by DaniellMesquita** [ElectronForConstruct/construct2-plugin#7]
@armaldio

**Comment by Armaldio** [comment]
What do you mean by that ?
Do you want an event to be triggered ?

**Comment by DaniellMesquita** [comment]
Yes.
You list files/folders and could add a tag to it; with a condition "listing is done" for triggering events.

**Comment by Armaldio** [comment]
The listing is synchronous, that means that every action is done after the other
You don't need a trigger to know when the listing is done.

See this example:

https://transfer.sh/MGFGv/project.capx

**Comment by danimesq** [comment]
Action you mean, is events?
When you do the event "for each", next events will only begin after previous is ok?

**Comment by Armaldio** [comment]
Yes

**Comment by danimesq** [comment]
Thank you
